### ISSUE TITLE
A `HTTPPARSE` check with `fields` can be created successfully, but fails to update

### ISSUE THREAD

**Issue by StanAngeloff** [NodePing/nodeping-ansible#5]
Given the following partial configuration:

```yaml
- checktype: HTTPPARSE
  label: 'WSS SSL'
  target: "https://domain.com/ping.txt"
  interval: 360
  fields:
    fields: '{"days": {"name": "days", "min": 7, "max": 9999}}'
```

When the task is run with `action: "create"` the check gets created successfully:

![image](https://user-images.githubusercontent.com/93127/70636629-8c8fb600-1c3e-11ea-9bce-d0a7f0d9e8a5.png)

If the same check is then updated using `action: "update"`, it results in a change and the check is corrupted/fails:

![image](https://user-images.githubusercontent.com/93127/70636904-00ca5980-1c3f-11ea-94aa-340ae25cbad7.png)

This fails even if `['fields']['fields']` is a dict.

I haven't been able to pinpoint the culprit. It may be the Python API or even something in the API implementation itself?

**Comment by NodePing** [comment]
It could be the way you're updating the check. The way you create the HTTPPARSE check is correct. When updating it, you shouldn't have to do

``` yaml
...
fields:
  fields: '{"days": {"name": "days", "min": 7, "max": 9999}}'
```

Rather, you can simply have:

``` yaml
fields: '{"days": {"name": "days", "min": 7, "max": 9999}}'
```

If you could, try doing this when you update:

``` yaml
nodeping:
  action: update
  checktype: HTTPPARSE
  fields: '{"days": {"name": "days", "min": 300, "max": 7777}}'
```

The reason why is because the field you are updating is called `fields` in the HTTPPARSE check.
